#pragma once

/*
 * Printer profile
 *
 * Everything here describes the MACHINE, not the firmware: gcode macro
 * names, the chamber sensor's object name, and the heater ceilings. The
 * defaults suit a stock Klipper printer.
 *
 * To build for your own machine, do NOT edit this file. Drop a
 * dt_printer_profile_local.h next to it defining only what differs:
 *
 *     #define DT_PROFILE_QUICK2_LABEL "GBP"
 *     #define DT_PROFILE_QUICK2_GCODE "GOOSE_PURGE"
 *
 * It is picked up automatically and is gitignored, so a personal setup
 * never lands in a commit. Every value below is a fallback for one it does
 * not define.
 *
 * Nothing here is required for the firmware to run: a macro the printer
 * does not define simply fails when pressed, and the on-screen error
 * reports Klipper's own reason.
 */

#if defined(__has_include)
#  if __has_include("dt_printer_profile_local.h")
#    include "dt_printer_profile_local.h"
#  endif
#endif

/*
 * Bed levelling.
 *
 * Z_TILT_ADJUST suits a 3-point bed (Voron Trident and similar). Use
 * QUAD_GANTRY_LEVEL on a gantry-levelled machine (Voron 2), or your own
 * wrapper macro.
 */
#ifndef DT_PROFILE_LEVEL_LABEL
#define DT_PROFILE_LEVEL_LABEL "Z tilt"
#endif

#ifndef DT_PROFILE_LEVEL_GCODE
#define DT_PROFILE_LEVEL_GCODE "Z_TILT_ADJUST"
#endif

/*
 * Two quick-access macros on the home page.
 *
 * There is no standard for these -- they are whatever printer.cfg defines.
 * CLEAN_NOZZLE is common enough to be a reasonable default; the second slot
 * is deliberately generic.
 */
#ifndef DT_PROFILE_QUICK1_LABEL
#define DT_PROFILE_QUICK1_LABEL "Clean Nozzle"
#endif

#ifndef DT_PROFILE_QUICK1_GCODE
#define DT_PROFILE_QUICK1_GCODE "CLEAN_NOZZLE"
#endif

#ifndef DT_PROFILE_QUICK2_LABEL
#define DT_PROFILE_QUICK2_LABEL "Purge"
#endif

#ifndef DT_PROFILE_QUICK2_GCODE
#define DT_PROFILE_QUICK2_GCODE "PURGE"
#endif

/*
 * Chamber temperature sensor.
 *
 * The Klipper object is "temperature_sensor <name>" -- set the name only.
 * If the printer has no such sensor the query still succeeds and Moonraker
 * returns null, so the Chamber column simply reads "Unavailable".
 */
#ifndef DT_PROFILE_CHAMBER_SENSOR
#define DT_PROFILE_CHAMBER_SENSOR "chamber"
#endif

/*
 * Heater ceilings for the on-screen numeric entry, mirroring the printer's
 * configured max_temp. Klipper rejects anything higher regardless; clamping
 * here means a capped number on screen instead of an error afterwards.
 */
#ifndef DT_PROFILE_NOZZLE_MAX_C
#define DT_PROFILE_NOZZLE_MAX_C 300
#endif

#ifndef DT_PROFILE_BED_MAX_C
#define DT_PROFILE_BED_MAX_C 120
#endif
